; Global settings for redshift
[redshift]
; Biological day and night temperatures
temp-day=6500
temp-night=4000

fade=1
transition=1

dawn-time=7:00-8:00
dusk-time=17:00-18:00

brightness-day=0.9
brightness-night=0.4

location-provider=manual
adjustment-method=randr

[manual]
lat=-22.5254868
lon=-50.8805522

[randr]
screen=0
