[main]
font=monospace:size=12
pad=5x5

[colors-dark]
# Kanagawa Wave Palette
foreground=dcd7ba
background=1f1f28

## Normal colors
regular0=090618 # sumiInk0
regular1=c34043 # autumnRed
regular2=76946a # boatCanalGreen
regular3=c0a36e # boatCanalYellow
regular4=7e9cd8 # crystalBlue
regular5=957fb8 # oniViolet
regular6=7fb4ca # aquaBlue
regular7=c8c093 # oldWhite

## Bright colors
bright0=727169 # fujiGray
bright1=e82424 # samuraiRed
bright2=98bb6c # springGreen
bright3=dca561 # autumnYellow
bright4=7fb4ca # blue-ish pop
bright5=938aa9 # oniViolet2
bright6=7aaaaa # freshAqua
bright7=dcd7ba # fujiWhite

## Selection/Misc
selection-foreground=dcd7ba
selection-background=2d4f67 # waveBlue2
